# I can't remember why I needed this?
# import = ["./extended-keys.yaml"]

[general]
import = ["./keybindings.toml"]

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "#d18616"
index = 16

[[colors.indexed_colors]]
color = "#ff938a"
index = 17

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#0e0d15"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#0e0d15"
foreground = "#a9b1d6"

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "sourcecodepro-with-nerd-fallback"
style = "Regular"

[font.offset]
x = 0
y = 0

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "none"
opacity = 0.3

[window.padding]
x = 0
y = 0
