[push]
  default = tracking
  autoSetupRemote = true
[commit]
  gpgsign = true
[pull]
  ff = only
[gpg]
  program = gpg2

[diff]
  colorMoved = default

[pager]
  diff = delta
  log = delta
  reflog = delta
  show = delta

[delta]
  navigate = true
  side-by-side = false
  tabs = 2
  true-color = always

  # Tokyo Night
  minus-style                   = syntax "#37222c"
  minus-non-emph-style          = syntax "#37222c"
  minus-emph-style              = syntax "#713137"
  minus-empty-line-marker-style = syntax "#37222c"
  line-numbers-minus-style      = "#914c54"
  plus-style                    = syntax "#20303b"
  plus-non-emph-style           = syntax "#20303b"
  plus-emph-style               = syntax "#2c5a66"
  plus-empty-line-marker-style  = syntax "#20303b"
  line-numbers-plus-style       = "#449dab"
  line-numbers-zero-style       = "#3b4261"

[interactive]
  diffFilter = delta --color-only

[init]
  defaultBranch = main

