# format = """$character"""
# right_format = """$git_status"""

[character]
success_symbol = "[ ](fg:#007cb1)"
error_symbol = "[ ](fg:red)"

[battery]
disabled = true

[package]
disabled = true

[directory]
style = "fg:#007cb1"

[kubernetes]
disabled = true

[gcloud]
disabled = true

[aws]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = "⚠️ "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
untracked = "[󰡯 ](fg:#ffc0cb)"
stashed = "[ ](blue)"
modified = "[ ](yellow)"
staged = '[$count](green)'
renamed = "➡️ "
deleted = " "

# [shell]
# disabled = false
