# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:

#n List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.43.0"
"tokyonight.nvim" = "4.11.0"
"neo-tree.nvim" = "3.28"
"tmux.nvim" = "scm"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.31.0"
"noice.nvim" = "4.9.0"
"rocks-git.nvim" = "2.5.2"
"gitsigns.nvim" = "0.9.0"
"lualine.nvim" = "scm"
"comment.nvim" = "0.8.0"
"telescope-ui-select.nvim" = "scm"
"rocks-treesitter.nvim" = "1.3.0"
tree-sitter-rust = "0.0.38"
tree-sitter-just = "0.0.36"
tree-sitter-toml = "0.0.31"
tree-sitter-python = "0.0.37"
tree-sitter-yaml = "0.0.30"
tree-sitter-javascript = "0.0.33"
friendly-snippets = "scm"
tree-sitter-nu = "0.0.29"
tree-sitter-gitcommit = "0.0.33"
tree-sitter-bash = "0.0.37"

[plugins."blink.cmp"]
git = "saghen/blink.cmp"
rev = "v0.10.0"

[plugins.novim-mode]
git = "tombh/novim-mode"
rev = "next"
opt = true

[plugins."telescope.nvim"]
git = "nvim-telescope/telescope.nvim"
rev = "0.1.8"

[plugins.nvim-scrollbar]
git = "petertriho/nvim-scrollbar"
rev = "6994eb9f73d5fdc36ee2c8717940e8c853e51a49"

[plugins."local-highlight.nvim"]
git = "tzachar/local-highlight.nvim"
rev = "c8e5fa9a945b7e99bccba2c9993b4d7a0327173d"

[treesitter]
auto_highlight = "all"
auto_install = "prompt" # true | false
disable = []

